config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
  }

  resources :users, only: [:index, :show, :edit, :update]
  resources :dance_events do
    resources :dance_event_participants, only: [:new] do
      collection do
        get :upload
        post :import
      end
    end
  end

  resources :dance_event_participants, only: [:create, :destroy]

  root "dance_events#index"
end

app/models/dance_event.rb
# == Schema Information
#
# Table name: dance_events
#
#  id          :bigint           not null, primary key
#  city        :string
#  country     :string           not null
#  description :text
#  end_date    :date
#  name        :string           not null
#  published   :boolean          default(FALSE)
#  start_date  :date
#  tags        :string           default([]), is an Array
#  website     :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_dance_events_on_published  (published)
#  index_dance_events_on_tags       (tags) USING gin
#  index_dance_events_on_user_id    (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class DanceEvent < ApplicationRecord
  belongs_to :organizer, class_name: "User", foreign_key: :user_id, inverse_of: :dance_events

  has_many :dance_event_participants, dependent: :destroy
  has_many :participants, through: :dance_event_participants, source: :user

  has_many :dance_event_instructors, dependent: :destroy
  has_many :instructors, through: :dance_event_instructors, source: :user

  validates :country, presence: true

  scope :tagged_one_of, ->(tags) { tags.present? ? where("tags && ARRAY[?]::varchar[]", tags) : all }
  scope :tagged_all_of, ->(tags) { tags.present? ? where("tags @> ARRAY[?]::varchar[]", tags) : all }
  scope :name_like, ->(name) { name.present? ? where("lower(name) like ?", "%#{name}%") : all }
  scope :published, -> { where(published: true) }

  def self.is_organizer(user)
    where(organizer: user)
  end

  def self.is_instructor(user)
    DanceEventInstructor.where(user_id: user).pluck(:dance_event_id)
  end

  def self.is_participant(user)
    DanceEventParticipant.where(user_id: user).pluck(:dance_event_id)
  end

  def self.viewable(user)
    published.or(is_organizer(user)).or(where(id: is_instructor(user) + is_participant(user)))
  end

  def self.instructors_name_like(name)
    name.present? ? left_joins(:instructors).where("lower(users.username) like ?", "%#{name}%") : all
  end

  def self.search(str)
    str = str.downcase
    instructors_name_like(str).or(tagged_one_of([str])).or(name_like(str))
  end

  def location
    city ? "#{city}, #{country}" : country
  end

  def instructors_names
    return "TBD" if instructors.blank?

    instructors.pluck("username").join(", ")
  end

  def involves(user)
    organizer == user || instructors.include?(user) || participants.include?(user)
  end
end

app/models/dance_event_participant.rb
# == Schema Information
#
# Table name: dance_event_participants
#
#  id             :bigint           not null, primary key
#  status         :string           default("registered")
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  dance_event_id :bigint           not null
#  user_id        :bigint           not null
#
# Indexes
#
#  index_dance_event_participants_on_dance_event_id              (dance_event_id)
#  index_dance_event_participants_on_dance_event_id_and_user_id  (dance_event_id,user_id) UNIQUE
#  index_dance_event_participants_on_status                      (status)
#  index_dance_event_participants_on_user_id                     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (dance_event_id => dance_events.id)
#  fk_rails_...  (user_id => users.id)
#
class DanceEventParticipant < ApplicationRecord
  belongs_to :dance_event
  belongs_to :user

  validates :user, uniqueness: {
    scope: :dance_event, message: I18n.t("dance_event_participants.validations.uniqueness")
  }
end

app/controllers/dance_event_participants_controller.rb
require "csv"

class DanceEventParticipantsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create destroy]
  before_action :verify_dance_event_and_user, only: %i[create]

  def new
    @dance_event = DanceEvent.find(params[:dance_event_id])
    @participant = DanceEventParticipant.new
  end

  def create
    @dance_event_participant = DanceEventParticipant.new(participant_params)

    if @dance_event_participant.save
      redirect_to dance_event_path(@dance_event), notice: "User successfully registered."
    else
      redirect_to new_dance_event_dance_event_participant_path(@dance_event),
                  notice: "User was already registered to this event."
      # render :new, status: :unprocessable_entity
    end
  end

  def destroy
    participation = DanceEventParticipant.find(params[:id])
    notice = if participation.destroy
               "#{participation.user.email} was successfully unregistered."
             else
               "Dance event participant could not be destroyed."
             end
    redirect_to dance_event_path(participation.dance_event), notice:
  end

  def import
    return redirect_to request.referer, notice: "No file added" if params[:file].nil?
    return redirect_to request.referer, notice: "Only CSV files allowed" unless params[:file].content_type == "text/csv"

    @results = ProcessDanceParticipantsCsv.perform(dance_event_id: params[:dance_event_id], csv: params[:file])

    flash[:notice] =
      "Users successfully registered: #{@results[0]}, Users already registered: #{@results[1]}, Users not found: #{@results[2]}"
    redirect_to dance_event_path(params[:dance_event_id])
  end

  def upload; end

  private

  def verify_dance_event_and_user
    @dance_event = DanceEvent.find(participant_params[:dance_event_id])
    @user = User.find(participant_params[:user_id])
  rescue ActiveRecord::RecordNotFound => e
    flash[:warning] = "Error occured! #{e.message}"
    redirect_to dance_events_path
  end

  def participant_params
    params.fetch(:dance_event_participant, {}).permit(:dance_event_id, :user_id)
  end
end

app/helpers/dance_event_participants_helper.rb
module DanceEventParticipantsHelper
  def users_options(participant_ids = [])
    if participant_ids.present?
      User.where.not(id: participant_ids).pluck(:email, :id)
    else
      User.pluck(:email, :id)
    end
  end
end

app/views/dance_event_participants/_dance_event_participant.html.erb
<tr id="<%= dom_id dance_event_participant.user %>" class="bg-white border-b dark:bg-gray-800 dark:border-gray-700
  hover:bg-gray-50 dark:hover:bg-gray-600">
  <td class="w-4 p-4">
    <div class="flex items-center">
      <input id="checkbox-table-search-1" type="checkbox" value="" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 
        rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 
        dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
      <label for="checkbox-table-search-1" class="sr-only">checkbox</label>
    </div>
  </td>
  <th scope="row" class="flex items-center px-6 py-4 text-gray-900 whitespace-nowrap dark:text-white">
    <img class="w-10 h-10 rounded-full" src=<%= user_gravatar_url %> alt="Jese image">
    <div class="pl-3">
      <div class="text-base font-semibold"><%= dance_event_participant.user.username %></div>
      <div class="font-normal text-gray-500"><%= dance_event_participant.user.email %></div>
    </div>
  </th>
  <td class="px-6 py-4">
    ---
  </td>
  <td class="px-6 py-4">
    <%= dance_event_participant.status %>
  </td>
  <td class="px-6 py-4">
    <div class="flex items-center">
      <div class="h-2.5 w-2.5 rounded-full bg-green-500 mr-2"></div>
      <% if @dance_event.organizer == current_user %>
        <%= button_to "Unregister", dance_event_participant, method: :delete %>
      <% else%>
        ---
      <% end %>
    </div>
  </td>
</tr>

app/views/dance_event_participants/new.html.erb
<h1>Add users to <%= @dance_event.name %></h1>
<%= form_with(model: @participant) do |form| %>
  <div>
    <%= form.hidden_field :dance_event_id, value: @dance_event.id %>
    <%= form.label :user_id, "Users list" %>
    <%= form.select :user_id, users_options(@dance_event.participant_ids) %>
    <%= form.submit "Add" %>
  </div>
<% end %>

app/views/dance_event_participants/upload.html.erb
<h2>Upload user registration</h2>
<%= form_tag import_dance_event_dance_event_participants_path, method: :post, multipart: true do %>
  <%= file_field_tag :file, accept: ".csv" %>
  <%= submit_tag "Import" %>
<% end %>