config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
  }

  resources :users, only: [:index, :show, :edit, :update]
  resources :dance_events do
    resources :dance_event_participants, only: [:new] do
      collection do
        get :upload
        post :import
      end
    end
  end

  resources :dance_event_participants, only: [:create, :destroy]

  root "dance_events#index"
end

app/models/dance_event.rb
# == Schema Information
#
# Table name: dance_events
#
#  id          :bigint           not null, primary key
#  city        :string
#  country     :string           not null
#  description :text
#  end_date    :date
#  name        :string           not null
#  published   :boolean          default(FALSE)
#  start_date  :date
#  tags        :string           default([]), is an Array
#  website     :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_dance_events_on_published  (published)
#  index_dance_events_on_tags       (tags) USING gin
#  index_dance_events_on_user_id    (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class DanceEvent < ApplicationRecord
  belongs_to :organizer, class_name: "User", foreign_key: :user_id, inverse_of: :dance_events

  has_many :dance_event_participants, dependent: :destroy
  has_many :participants, through: :dance_event_participants, source: :user

  has_many :dance_event_instructors, dependent: :destroy
  has_many :instructors, through: :dance_event_instructors, source: :user

  validates :country, presence: true

  scope :tagged_one_of, ->(tags) { tags.present? ? where("tags && ARRAY[?]::varchar[]", tags) : all }
  scope :tagged_all_of, ->(tags) { tags.present? ? where("tags @> ARRAY[?]::varchar[]", tags) : all }
  scope :name_like, ->(name) { name.present? ? where("lower(name) like ?", "%#{name}%") : all }
  scope :published, -> { where(published: true) }

  def self.is_organizer(user)
    where(organizer: user)
  end

  def self.is_instructor(user)
    DanceEventInstructor.where(user_id: user).pluck(:dance_event_id)
  end

  def self.is_participant(user)
    DanceEventParticipant.where(user_id: user).pluck(:dance_event_id)
  end

  def self.viewable(user)
    published.or(is_organizer(user)).or(where(id: is_instructor(user) + is_participant(user)))
  end

  def self.instructors_name_like(name)
    name.present? ? left_joins(:instructors).where("lower(users.username) like ?", "%#{name}%") : all
  end

  def self.search(str)
    str = str.downcase
    instructors_name_like(str).or(tagged_one_of([str])).or(name_like(str))
  end

  def location
    city ? "#{city}, #{country}" : country
  end

  def instructors_names
    return "TBD" if instructors.blank?

    instructors.pluck("username").join(", ")
  end

  def involves(user)
    organizer == user || instructors.include?(user) || participants.include?(user)
  end
end

app/controllers/dance_events_controller.rb
class DanceEventsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_dance_event, only: %i[show edit update destroy]

  # GET /dance_events or /dance_events.json
  def index
    @dance_events = DanceEvent.viewable(current_user)
    return if params[:search].blank?

    @dance_events = DanceEvent.viewable(current_user).search(params[:search])
  end

  # GET /dance_events/1 or /dance_events/1.json
  def show
    unless @dance_event.published || @dance_event.involves(current_user)
      return redirect_to dance_events_path, notice: "404 Not Found"
    end

    @participants = @dance_event.dance_event_participants.includes(:user)
  end

  # GET /dance_events/new
  def new
    @dance_event = DanceEvent.new
  end

  # GET /dance_events/1/edit
  def edit
    unless @dance_event.organizer == current_user
      return redirect_to dance_events_path, notice: "401 Unauthorized"
    end

    render :edit
  end

  # POST /dance_events or /dance_events.json
  def create
    @dance_event = DanceEvent.new(dance_event_params)
    @dance_event.user_id = current_user.id

    respond_to do |format|
      if @dance_event.save
        format.html { redirect_to dance_event_path(@dance_event), notice: "Dance event was successfully created." }
        format.json { render :show, status: :created, location: @dance_event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dance_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dance_events/1 or /dance_events/1.json
  def update
    respond_to do |format|
      if @dance_event.update(dance_event_params)
        format.html { redirect_to dance_event_path(@dance_event), notice: "Dance event was successfully updated." }
        format.json { render :show, status: :ok, location: @dance_event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dance_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dance_events/1 or /dance_events/1.json
  def destroy
    @dance_event.destroy

    respond_to do |format|
      format.html { redirect_to dance_events_path, notice: "Dance event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_dance_event
    @dance_event = DanceEvent.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def dance_event_params
    params.fetch(:dance_event, {}).permit(
      :name, :description, :start_date, :end_date, :country, :city, :website, :search
    )
  end
end

app/helpers/dance_events_helper.rb
module DanceEventsHelper
end

app/views/dance_events/_dance_event.html.erb
<div id="<%= dom_id dance_event %>" class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
  <!-- <a href="#">
    TODO: Add images to events
    <img class="rounded-t-lg" src="/docs/images/blog/image-1.jpg" alt="" />
  </a> -->
  <div class="p-5">
    <h5 class="mb-2 truncate text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= dance_event.name %></h5>
    <p class="text-sm font-medium text-gray-800">
      Organizer: <a href=<%=user_path(dance_event.organizer) %> class="text-blue-700">
        <%= dance_event.organizer.username %>
      </a>
    </p>
    <p class="text-sm font-medium text-gray-800">
      Dates: 
      <time>
        <%= dance_event.start_date %>
      </time> to <time>
        <%= dance_event.end_date %>
      </time>
    </p>
    <p class="text-sm font-medium text-gray-800">Location: <%= dance_event.location %></p>
    <p class="text-sm font-medium text-gray-800">Instructors: <%= dance_event.instructors_names %></p>
    <p class="my-6 h-24 line-clamp-3 md:line-clamp-4 font-normal text-gray-500 dark:text-gray-400"><%= dance_event.description %></p>
    <a href=<%= dance_event_path(dance_event) %> class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
      Learn More
      <svg class="w-3.5 h-3.5 ml-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
        viewBox="0 0 14 10">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
          d="M1 5h12m0 0L9 1m4 4L9 9" />
      </svg>
    </a>
  </div>
</div>

app/views/dance_events/_form.html.erb
<%= form_with(model: dance_event) do |form| %>
  <% if dance_event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dance_event.errors.count, "error") %> prohibited this dance_event from being saved:</h2>
      <ul>
        <% dance_event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.label :description %>
    <%= form.text_area :description %>
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
    <%= form.label :country %>
    <%= form.text_field :country %>
    <%= form.label :city %>
    <%= form.text_field :city %>
    <%= form.label :website %>
    <%= form.text_field :website %>
    <%= form.label :published %>
    <%= form.check_box :published %>
    <%= form.submit %>
  </div>
<% end %>

app/views/dance_events/edit.html.erb
<h1>Editing dance event</h1>

<%= render "form", dance_event: @dance_event %>

<br>

<div>
  <%= link_to "Show this dance event", @dance_event %> |
  <%= link_to "Back to dance events", dance_events_path %>
</div>

app/views/dance_events/index.html.erb
<h2 class="mb-6 text-4xl font-extrabold dark:text-white">Dance Events</h2>
<% if user_signed_in? %>
  <%= link_to "New dance event", new_dance_event_path, class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
<% else %>
  You have to be logged in to create dance events
<% end %>
<%= form_tag dance_events_path, class: "max-w-md mx-auto", method: :get do %>
  <label for="search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
  <div class="relative">
    <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
      <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
      </svg>
    </div>
    <%= text_field_tag :search, params[:search], placeholder: "search" %>
    <button type="submit" class="text-white absolute end-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 
        focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 
        dark:hover:bg-blue-700 dark:focus:ring-blue-800">
      Search
    </button>
  </div>
<% end %>
<ul id="dance_events" role="list" class="grid grid-cols-1 gap-2 md:grid-cols-3 my-6">
  <%= render @dance_events %>
</ul>

app/views/dance_events/new.html.erb
<h1>New dance event</h1>
<%= render "form", dance_event: @dance_event %>
<br>
<div>
  <%= link_to "Back to dance events", dance_events_path %>
</div>

app/views/dance_events/show.html.erb
<div class="p-5">
  <h5 class="mb-2 truncate text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
    <%= @dance_event.name %>
  </h5>
  <p class="text-sm font-medium text-gray-800">
    Organizer: <a href=<%=user_path(@dance_event.organizer) %> class="text-blue-700">
      <%= @dance_event.organizer.username %>
    </a>
  </p>
  <p class="text-sm font-medium text-gray-800">
    Dates: <time><%= @dance_event.start_date %></time> to <time><%= @dance_event.end_date %></time>
  </p>
  <p class="text-sm font-medium text-gray-800">Location: <%= @dance_event.location %></p>
  <p class="text-sm font-medium text-gray-800">
    Instructors: <%= @dance_event.instructors_names %>
  </p>
  <p class="my-6 h-24 line-clamp-3 md:line-clamp-4 font-normal text-gray-500 dark:text-gray-400">
    <%= @dance_event.description %>
  </p>
  <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <div class="flex items-center justify-between pb-4 bg-white dark:bg-gray-900">
      <div>
        <button id="dropdownActionButton" data-dropdown-toggle="dropdownAction" class="inline-flex items-center text-gray-500 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-3 py-1.5 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" type="button">
          <span class="sr-only">Action button</span>
          Action
          <svg class="w-2.5 h-2.5 ml-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
          </svg>
        </button>
        <!-- Dropdown menu -->
        <div id="dropdownAction" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
          <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownActionButton">
            <li>
              <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Reward</a>
            </li>
            <li>
              <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Promote</a>
            </li>
            <li>
              <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Activate account</a>
            </li>
          </ul>
          <div class="py-1">
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Delete User</a>
          </div>
        </div>
      </div>
      <label for="table-search" class="sr-only">Search</label>
      <div class="relative">
        <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
          <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
          </svg>
        </div>
        <input type="text" id="table-search-users" class="block p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search for users">
      </div>
    </div>
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr>
          <th scope="col" class="p-4">
            <div class="flex items-center">
              <input id="checkbox-all-search" type="checkbox" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
              <label for="checkbox-all-search" class="sr-only">checkbox</label>
            </div>
          </th>
          <th scope="col" class="px-6 py-3">
            Name
          </th>
          <th scope="col" class="px-6 py-3">
            Position
          </th>
          <th scope="col" class="px-6 py-3">
            Status
          </th>
          <th scope="col" class="px-6 py-3">
            Action
          </th>
        </tr>
      </thead>
      <tbody>
        <%= render @participants %>
      </tbody>
    </table>
  </div>
</div>
<% if @dance_event.organizer == current_user %>
  <div>
    <%= link_to "Edit this dance event", edit_dance_event_path(@dance_event) %> |
    <%= button_to "Destroy this dance event", @dance_event, method: :delete %>
    <%= link_to "Add participants", new_dance_event_dance_event_participant_path(@dance_event) %>
    <%= link_to "Import participants", upload_dance_event_dance_event_participants_path(@dance_event) %>
  </div>
<% end %>