config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
  }

  resources :users, only: [:index, :show, :edit, :update]
  resources :dance_events do
    resources :dance_event_participants, only: [:new] do
      collection do
        get :upload
        post :import
      end
    end
  end

  resources :dance_event_participants, only: [:create, :destroy]

  root "dance_events#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Big Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.css" rel="stylesheet" />
  </head>
  <body class="bg-white dark:bg-gray-900 mx-auto container">
    <nav class="bg-white border-gray-200 dark:bg-gray-900">
      <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href=<%= root_path %> class="flex items-center">
          <%# <img src="https://flowbite.com/docs/images/logo.svg" class="h-8 mr-3" alt="Flowbite Logo" /> %>
          <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Events Baby!</span>
        </a>
        <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
          <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 
            md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
            <li>
              <a href=<%= dance_events_path %> class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 
                md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 
                dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">
                Events
              </a>
            </li>
            <li>
              <a href=<%= users_path %> class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 
                md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 
                dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">
                Organizers
              </a>
            </li>
            <% if user_signed_in? %>
              <li>
                <a href=<%= user_path(current_user) %> class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 
                  md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 
                  dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">
                  Settings
                </a>
              </li>
              <li>
                <%= button_to "Sign out", destroy_user_session_path, method: :delete, 
                  class: "block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent 
                  md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 
                  dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
              </li>
            <% else %>
              <li>
                <a href=<%= new_user_session_path %> class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 
                  md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 
                  dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">
                  Sign in
                </a>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="p-4 mx-auto max-w-screen-xl">
      <% flash.each do |type, msg| %>
        <% if type == "notice" %>
          <div class="p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400" role="alert">
            <span class="font-medium"><%= msg %></span>
          </div>
        <% elsif type == "alert" %>
          <div class="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400" role="alert">
            <span class="font-medium"><%= msg %></span>
          </div>
        <% elsif type == "info" %>
          <div class="p-4 mb-4 text-sm text-blue-800 rounded-lg bg-blue-50 dark:bg-gray-800 dark:text-blue-400" role="alert">
            <span class="font-medium"><%= msg %></span>
          </div>
        <% elsif type == "warning" %>
          <div class="p-4 mb-4 text-sm text-yellow-800 rounded-lg bg-yellow-50 dark:bg-gray-800 dark:text-yellow-300" role="alert">
            <span class="font-medium"><%= msg %></span>
          </div>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
    <%= javascript_importmap_tags %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>
  </body>
</html>